x-common: &common
  build:
    args: &common-build-args
      UID: ${UID}
  env_file: .env
  user: ${UID}
  restart: always

services:
  init:
    <<: *common
    profiles:
      - init
    image: agrocery/setup:0.1.0
    build:
      context: setup
      args:
        <<: *common-build-args
        ENV: prd
    container_name: agrocery-init
    hostname: agrocery-init
    restart: no
    command: ["python", "/app/src/initialize.py"]

  clean:
    <<: *common
    profiles:
      - clean
    image: agrocery/setup:0.1.0
    build:
      context: setup
      args:
        <<: *common-build-args
        ENV: prd
    container_name: agrocery-clean
    hostname: agrocery-clean
    restart: no
    command: ["python", "/app/src/clean.py"]

  #########################################################
  # Development
  #########################################################
  agents-dev:
    <<: *common
    profiles:
      - dev
    image: agrocery/agents:0.1.0
    build:
      context: agents
      args:
        <<: *common-build-args
        ENV: dev
    container_name: agrocery-agents-dev
    hostname: agrocery-agents-dev
    ports:
      - 10000:8000
    volumes:
      - ./agents:/app

  view-dev:
    <<: *common
    profiles:
      - dev
    image: agrocery/view:0.1.0
    build:
      context: view
      args:
        <<: *common-build-args
        ENV: dev
    container_name: agrocery-view-dev
    hostname: agrocery-view-dev
    environment:
      STREAMLIT_SERVER_RUN_ON_SAVE: true
    ports:
      - 10001:8501
    volumes:
      - ./view:/app

  #########################################################
  # Production
  #########################################################
  agents-prd:
    <<: *common
    profiles:
      - prd
    image: agrocery/agents:0.1.0
    build:
      context: agents
      args:
        <<: *common-build-args
        ENV: prd
    container_name: agrocery-agents-prd
    hostname: agrocery-agents-prd
    ports:
      - 11000:8000

  view-prd:
    <<: *common
    profiles:
      - prd
    image: agrocery/view:0.1.0
    build:
      context: view
      args:
        <<: *common-build-args
        ENV: prd
    container_name: agrocery-view-prd
    hostname: agrocery-view-prd
    environment:
      STREAMLIT_SERVER_RUN_ON_SAVE: true
    ports:
      - 11001:8501

networks:
  default:
    name: agrocery
